Some suggestions for the setup pihole script
piperka07/Setup_Pi-Hole pull request #1
Opened 2021-12-21 18:21 UTC by nlazarov

Видно днес бях отпуска :)

2021-12-21 18:26 UTC, nlazarov commented on Setup_Pi-Hole.sh
> +DisableBluetooth="yes"
не ми трябва bluetooth, затова си мисля, че може да има опция да се спира

2021-12-21 18:26 UTC, nlazarov commented on Setup_Pi-Hole.sh
> +Interface=$(ip a | grep -v 127.0.0.1 | grep inet | awk '{ print $NF }')
Това е предложение за по-кратка проверка. Може и да го махна, ако мислиш, че би било чупливо.

2021-12-21 18:26 UTC, nlazarov commented on Setup_Pi-Hole.sh
> +fi
Беше писал по едно време за това. Успях да го намеря и като предложение в документацията на rpi. Мисля си, че е добра идея да го има в скрипта.

2021-12-21 18:26 UTC, nlazarov commented on Setup_Pi-Hole.sh
> +fi
Проверка да не прибавя 2 пъти този сетинг.

2021-12-21 18:26 UTC, nlazarov commented on Setup_Pi-Hole.sh
> +[[ -f /etc/dnsmasq.d/02-dnscrypt.conf ]] && sed -i "/proxy-dnssec/d" /etc/dnsmasq.d/02-dnscrypt.conf
^^^

2021-12-21 18:26 UTC, nlazarov commented on Setup_Pi-Hole.sh
> +echo "deb http://packages.azlux.fr/debian/ $DebianRelease main" | sudo tee /etc/apt/sources.list.d/azlux.list
Днес инсталирах `bullseye`. По-добре да е променлива

2021-12-22 12:01 UTC, nlazarov commented on Setup_Pi-Hole.sh
> +apt install neovim locate rsync
Откакто използвам neovim, не мога да намеря причина да се върна на `vim`. Командата отново е `vim`, но може да се ползва и `nvim`

2021-12-23 21:22 UTC, piperka07 requested changes
Interface=$(ifconfig | grep -v "127.0.0.1" | grep -B 1 inet\ | grep -v inet | cut -d ':' -f 1)

should remain.

2021-12-23 21:28 UTC, piperka07 approved these changes

2021-12-23 21:28 UTC, merged